services:
  web:
    image: nginx:1.27.4
    container_name: nginx
    volumes:
      - ./config/:/etc/nginx/conf.d/
      - ./site-content:/var/www/html
    ports:
      - 80:80
    networks:
      private_lab:
        ipv4_address: 192.168.100.40

networks:
  private_lab:
    external: true
