services:
  speedtest:
    container_name: openspeedtest
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      private_lab:
        ipv4_address: 192.168.100.50
    image: openspeedtest/latest:v2.0.6
    restart: unless-stopped

networks:
  private_lab:
    external: true
