services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:0.15.10
    restart: unless-stopped
    volumes:
      - ./homarr/configs:/app/data/configs
      - ./homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SECRET_ENCRYPTION_KEY=<SECRET_ENCRYPTION_KEY>
    ports:
      - 7575:7575
    networks:
      private_lab:
        ipv4_address: 192.168.100.20

networks:
  private_lab:
    external: true
