# Managed by dnsmasq WebGUI
# Log DNS queries
log-queries
# Listen on fixed ip address
listen-address=192.168.100.10
# Configure DNS caching
cache-size=1000
# Read local DNS entries from the managed hosts file
addn-hosts=/etc/dnsmasq.hosts
# Set DNS forwarders
server=8.8.8.8
server=8.8.4.4
# Custom DNS entries
